FROM golang:1.24-alpine AS builder
RUN apk add --no-cache gcc musl-dev
WORKDIR /app
COPY . .
ENV GOTOOLCHAIN=auto
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /snitch-host-agent ./cmd/hostagent

FROM scratch
COPY --from=builder /snitch-host-agent /snitch-host-agent
ENTRYPOINT ["/snitch-host-agent"]
